services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.213.19.169:8981
    container_name: linkedin-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
